[package]
name = "bevy_sandbox"
authors = ["hao.zhen <i_zhenhao@163.com>"]
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy_asset_loader = { version = "0.14", features = ["stageless"] }
iyes_loopless = "0.9"
bevy_match3 = "0.2.0"